#%RAML 1.0
---
title: Mapogram API
baseUri: http://mapogram.dejan7.com/api
version: v1

----------------------
### Important: All requests should have `Accept: application/json` header set!
----------------------

/login:
    post:
        body:
            username
            password
        responses:
            200:
                body:
                    application/json:
                    example: |
                    {
                        "data": {token: "a5x3425....."},
                        "status": 200
                    }
            422:
                body:
                    application/json:
                    example: |
                    {
                        "data": {error: 'Wrong username and/or password.'},
                        "status": 422
                    }

/logout:
    post:
        headers:
            Authorization: Bearer apiTokenString
        body:
        responses:
            200:
                body:
                    application/json:
                    example: |
                    {
                        "data": [],
                        "status": 200
                    }


/register:
    post:
        body:
            username
            email
            password
            password_confirmation
        responses:
            200:
                body:
                    application/json:
                    example: |
                    {
                        "data": [],
                        "status": 200
                    }
            422:
                body:
                    application/json:
                    example: |
                    {
                        "data": {username: 'Username is required',...},
                        "status": 422
                    }

/users/{username}
    get:
        responses:
            200:
                body:
                    application/json:
                    example: |
                    {
                        "id": 1,
                        "username": "petar",
                        "email": "pera@pera.com",
                        "first_name": null,
                        "last_name": null,
                        "avatar": "http://mapogram.dev/asda.jpg",
                        "phone_number": null,
                        "created_at": "2017-08-27 11:50:54",
                        "updated_at": "2017-08-27 12:10:54"
                    }
    patch:
        headers:
            Authorization: Bearer apiTokenString
        body:
            username
            email
            phone_number
            first_name
            last_name
            avatar: file

/users/{username}/photos
    get:
        responses:
            200:
                body:
                    application/json:
                    example: |
                    {
                        "id": 1,
                        "username": "petar",
                        "email": "pera@pera.com",
                        "first_name": null,
                        "last_name": null,
                        "avatar": "http://mapogram.dev/asda.jpg",
                        "phone_number": null,
                        "created_at": "2017-08-27 11:50:54",
                        "updated_at": "2017-08-27 12:10:54"
                        "photos": [
                            {
                                "id": 2,
                                "user_id": 1,
                                "filename": "59a7e2316f5fc.jpg",
                                "location": "21.899593,43.320495",
                                "url": "http://mapogram.dev/images/test.jpg",
                                "description": "demo photo",
                                "categories": "#sport",
                                "likes": 0,
                                "created_at": "2017-08-31 10:17:21",
                                "updated_at": "2017-08-31 10:17:21",
                            },
                        ]
                    }

/users/toplist
    get:
        responses:
            200:
                body:
                    application/json:
                    example: |
                    [
                        {
                            "id": 1,
                            "username": "petar",
                            "avatar": "asdasd",
                            "total_likes": 555
                        },
                        {
                            "id": 1,
                            "username": "petar",
                            "avatar": "asdasd",
                            "total_likes": 444
                        },....
                    ]


/users/{username1}/friends/{username2}
    post:
        description: Used so that username1 and username 2 become friends:
        headers:
            Authorization: Bearer apiTokenString
        body:
        responses:
            200:
                body:
                    application/json:
                    example: |
                    {
                        "message": "success"
                    }

/photos
    post:
        description: Uploads a photo
        headers:
            Authorization: Bearer apiTokenString
        body:
            img (base64 e.g. send a string like data:image/gif;base64,R0lGODlhZ....
            lng (e.g. 21.899593)
            lat (e.g. 21.899593),
            description
            categories (e.g. '#people #nature'
        responses:
            200:
                body:
                    application/json:
                    example: |
                    {
                        "message": "success"
                    }
/photos/{id}
    get:
        description: Get a single photo with author and comments
        headers:
            Authorization: Bearer apiTokenString
        responses:
            200:
                body:
                    application/json:
                    example: |
                    {
                        "id": 2,
                        "user_id": 1,
                        "filename": "59a7e2316f5fc.jpg",
                        "location": "21.899593,43.320495",
                        "created_at": "2017-08-31 10:17:21",
                        "updated_at": "2017-08-31 14:59:58",
                        "likes": 3,
                        "url": "http://mapogram.dev/img/59a7e2316f5fc.jpg",
                        "comments": [
                            {
                                "id": 1,
                                "user_id": 1,
                                "photo_id": 2,
                                "text": "hello world",
                                "created_at": "2017-08-31 14:47:06",
                                "updated_at": "2017-08-31 14:47:06",
                                "user": {
                                    "id": 1,
                                    "username": "petar",
                                    "avatar": null,
                                }
                            }
                        ],
                        "user": {
                            "id": 1,
                            "username": "petar",
                            "avatar": null,
                        }
                    }

/photos/{id}/likes
    post:
        description: like a photo
        headers:
            Authorization: Bearer apiTokenString
        responses:
            200:
                body:
                    application/json:
                    example: |
                    {
                        "message": 'success'
                    }

/photos/{id}/comments
    post:
        description: Add a comment to a photo
        headers:
            Authorization: Bearer apiTokenString
        body:
            text
        responses:
            200:
                body:
                    application/json:
                    example: |
                    {
                        "message": "success"
                    }

/photos/{location}/{distance}/{categories?}
    get:
        description: Returns all images in a $distance from $location
        queryParams:
            location ('lng,lat' e.g. 21.899593,21.899593)
            distance (IN METERS e.g. 5000)
        categories: OPTIONAL comma separated list of categories. only photos with those categories will be returned (e.g. people,sport)
        responses:
            200:
                body:
                    application/json:
                    example: |
                    {[
                        {
                            "id": 2,
                            "user_id": 1,
                            "filename": "59a7e2316f5fc.jpg",
                            "location": "21.899593,43.320495",
                            "url": "http://mapogram.dev/images/test.jpg",
                            "description": "demo photo",
                            "categories": "#sport",
                            "likes": 0,
                            "created_at": "2017-08-31 10:17:21",
                            "updated_at": "2017-08-31 10:17:21",
                        },
                        {
                            "id": 3,
                            "user_id": 1,
                            "filename": "59a7e2316f5fc.jpg",
                            "location": "21.899593,43.320495",
                            "url": "http://mapogram.dev/images/test.jpg"
                            "description": "demo photo",
                            "categories": "#sport",
                            "likes": 0,
                            "created_at": "2017-08-31 10:17:21",
                            "updated_at": "2017-08-31 10:17:21"
                        },...
                    ]}

/location/exchange
    post:
        description: Expects to receive user's current lng,lat. Responds with friends locations. Useful for polling.
        headers:
            Authorization: Bearer apiTokenString
        body:
            location (lng,lat)
        responses:
            200:
                body:
                    application/json:
                    example: |
                    {[
                        {
                            "id": 2,
                            "username": "peter",
                            "avatar": "59a7e2316f5fc.jpg",
                            "location": "21.899593,21.899593" //lng,lat
                        },
                        {
                            "id": 3,
                            "username": "peter",
                            "avatar": "59a7e2316f5fc.jpg",
                            "location": "21.899593,21.899593" //lng,lat
                        },..
                    ]}

categories
    get:
        headers:
            Authorization: Bearer apiTokenString
        body:
            text
        responses:
            200:
                body:
                    application/json:
                    example: |
                    [
                        {
                            "id": 1,
                            "name": "#nature"
                        },
                        {
                            "id": 2,
                            "name": "#sport"
                        },
                        {
                            "id": 3,
                            "name": "#fitness"
                        },....
                    ]